# Generated by Django 4.2.24 on 2025-09-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('duration_hours', models.PositiveIntegerField(default=2)),
                ('setup_time', models.PositiveIntegerField(default=30)),
                ('genres', models.JSONField(default=list)),
                ('instruments_needed', models.JSONField(default=list)),
                ('band_size_min', models.PositiveIntegerField(default=1)),
                ('band_size_max', models.PositiveIntegerField(default=5)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_type', models.CharField(choices=[('per_gig', 'Per Gig'), ('per_hour', 'Per Hour'), ('negotiable', 'Negotiable')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], max_length=20)),
                ('original_music_required', models.BooleanField(default=False)),
                ('cover_music_required', models.BooleanField(default=True)),
                ('sound_system_provided', models.BooleanField(default=True)),
                ('lighting_provided', models.BooleanField(default=True)),
                ('backline_provided', models.BooleanField(default=False)),
                ('special_requirements', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('ai_generated_description', models.TextField(blank=True)),
                ('ai_generated_marketing_copy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='users.venueprofile')),
            ],
            options={
                'verbose_name': 'Gig',
                'verbose_name_plural': 'Gigs',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('proposed_setlist', models.JSONField(default=list)),
                ('proposed_duration', models.PositiveIntegerField(default=2)),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('portfolio_links', models.JSONField(default=list)),
                ('audio_samples', models.JSONField(default=list)),
                ('video_samples', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('venue_notes', models.TextField(blank=True)),
                ('musician_notes', models.TextField(blank=True)),
                ('ai_generated_cover_letter', models.TextField(blank=True)),
                ('ai_generated_setlist', models.JSONField(default=list)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigs.gig')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_applications', to='users.musicianprofile')),
            ],
            options={
                'verbose_name': 'Gig Application',
                'verbose_name_plural': 'Gig Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('gig', 'musician')},
            },
        ),
    ]
