# Generated by Django 4.2.24 on 2025-09-04 08:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('musician', 'Musician'), ('venue', 'Venue Owner'), ('admin', 'Administrator')], default='musician', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VenueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_type', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('has_stage', models.BooleanField(default=True)),
                ('has_sound_system', models.BooleanField(default=True)),
                ('has_lighting', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_food', models.BooleanField(default=False)),
                ('has_alcohol', models.BooleanField(default=False)),
                ('preferred_genres', models.JSONField(default=list)),
                ('preferred_instruments', models.JSONField(default=list)),
                ('booking_lead_time', models.PositiveIntegerField(default=7)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('venue_photos', models.JSONField(default=list)),
                ('ai_generated_description', models.TextField(blank=True)),
                ('ai_generated_marketing_copy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venue Profile',
                'verbose_name_plural': 'Venue Profiles',
            },
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_instrument', models.CharField(max_length=100)),
                ('instruments', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('band_name', models.CharField(blank=True, max_length=100)),
                ('is_solo_artist', models.BooleanField(default=False)),
                ('band_size', models.PositiveIntegerField(default=1)),
                ('setlist_examples', models.JSONField(default=list)),
                ('original_music', models.BooleanField(default=False)),
                ('cover_music', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('per_gig_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability_schedule', models.JSONField(default=dict)),
                ('travel_distance', models.PositiveIntegerField(default=50)),
                ('portfolio_links', models.JSONField(default=list)),
                ('audio_samples', models.JSONField(default=list)),
                ('video_samples', models.JSONField(default=list)),
                ('ai_generated_bio', models.TextField(blank=True)),
                ('ai_generated_setlist', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musician Profile',
                'verbose_name_plural': 'Musician Profiles',
            },
        ),
    ]
