# Generated by Django 4.2.24 on 2025-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='user_notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
